### ISSUE TITLE
Add More Walls

### ISSUE THREAD

**Issue by jonasnoki** [jonasnoki/ca_homework#3]
Currently there is only on at z=0. Let's create 6 in total so that we have an enclosed space (like a room).

https://github.com/jonasnoki/ca_homework/blob/5b3c30e19848de2191ab08e49d9ce02d2f861dc3/src/Simulation.ts#L38

**Comment by JannisWolf** [comment]
Could be also a good one for me to get started:D

**Comment by JannisWolf** [comment]
closed by bebfc8ec868b51c391f734e8c8d5d4e6b10902e3
